# Site settings
title:          binaryflavor techblog
description:    "binaryflavor techblog"
baseurl:        ""
url:            "https://binaryflavor.com"

# Google Analytics
google_analytics: UA-132330224-1

# Author
author:
  name:         Juneseok Byun
  url:          https://facebook.com/byunjuneseok
  email:        byunjuneseok@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         byunjuneseok-github-io

collections:
  algorithm:
    output: true
  playlist:
    output: true